[[redirects]]
  from = "/login/*"
  to = "https://onlinememo.kr/login/:splat"
  status = 200

[[redirects]]
  from = "/auth/*"
  to = "https://onlinememo.kr/auth/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200