[[redirects]]
  from = "https://onlinememo.netlify.app/login/*"
  to = "https://www.onlinememo.kr/login/:splat"
  status = 200

[[redirects]]
  from = "https://onlinememo.netlify.app/auth/*"
  to = "https://www.onlinememo.kr/auth/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200